---
driver:
  name: vagrant

provisioner:
  product_name: chef
  product_version: latest

verifier:
  name: inspec
  inspec_tests:
  - test/integration/default

platforms:
  - name: ubuntu16
    driver:
      box: bento/ubuntu-16.04
      box_url: https://vagrantcloud.com/bento/ubuntu-16.04
      box_check_update: true

  - name: ubuntu18
    driver:
      box: bento/ubuntu-18.04
      box_url: https://vagrantcloud.com/bento/ubuntu-18.04
      box_check_update: true


suites:
  - name: default
    run_list:
    - recipe[msp::default]
    verifier:
      controls:
      - directories
      - packages

