---
driver:
  name: vagrant

provisioner:
  product_name: chef
  product_version: 18
  chef_license: accept

verifier:
  name: inspec
  inspec_tests:
  - test/integration/default

platforms:
  - name: ubuntu18
    driver:
      box: bento/ubuntu-18.04
      box_url: https://vagrantcloud.com/bento/ubuntu-18.04
      box_check_update: true

  - name: ubuntu23-arm
    driver:
      box: bento/ubuntu-23.04-arm64
      box_url: https://vagrantcloud.com/bento/ubuntu-23.04-arm64
      box_check_update: true

  - name: macos-high-sierra
    driver:
      box: vagrant-appunite/macos10.13.5
      box_url: https://vagrantcloud.com/vagrant-appunite/macos10.13.5
      box_check_update: true

suites:
  - name: msp
    provisioner:
      policyfile_path: ./Policyfile.rb
    verifier:
      controls:
      - directories
      - packages

